# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2096f5ce173ddb1749acfa188530a6d91d430463706ac6786f92c336acc98a104a8ae5c7e5c9a540d8130ab812532dda5f9bc496e47be028b0db798f7e65531d

test:
  secret_key_base: 8ef3684f4a19fa44536609da4026233166561b84a1ddebc32e270a7d467a6e47e87749c6b7e3bcefb76c3c128634e0af31a7f0a6b42b0506227d4c1695e56891

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
