# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f741ef3f2f6148a342fbada99d8d2131bb557484b95b15983e45c5f80c74f6a0604a052fc1f2d29dc190d040e445d69ce3b3562aaf2e0c2c93b6cd72bfebe870

test:
  secret_key_base: 852397bbed7456f2bb9e1511cc4c6fb4ed0ce800f2cae2c68746e081e3b7081bd3d4528b2b2f3e9ad26d9599abb3f1f25770e0792bc07af0e52b7560c8c8ee36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
